/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Objetos.Usuario;
import bd.ConexionBase;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian
 */
public class frmCambioClave extends javax.swing.JFrame {

    /** Creates new form frmCambioClave */
    public frmCambioClave(String cuenta) {
        initComponents();
        
        //obteniendo datos de usuario
        ConexionBase c = new ConexionBase();
        try{
            c.conectar();
            Usuario usrAct = c.obtenerDatosUsuario(cuenta);
            tfNombreUsr.setText(usrAct.getNombre());
            tfCuentausr.setText(usrAct.getCuenta());
        }catch (Exception e){
            System.out.println(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNombreUsr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pfpass1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        pfpass2 = new javax.swing.JPasswordField();
        btLimpiar = new javax.swing.JButton();
        btCambiarClave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCuentausr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cambio de Clave - Usuario");

        tfNombreUsr.setEditable(false);
        tfNombreUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreUsrActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Ingrese Nueva Clave:");

        jLabel3.setText("Confirme Nueva Clave:");

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        btCambiarClave.setText("Cambiar");
        btCambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambiarClaveActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese una clave que contenga letras y numeros, minimo 6 caracteres.");

        jLabel5.setText("Cuenta:");

        tfCuentausr.setEditable(false);
        tfCuentausr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCuentausrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pfpass1)
                                    .addComponent(pfpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175)
                                .addComponent(btCambiarClave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfCuentausr))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tfNombreUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombreUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCuentausr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pfpass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pfpass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCambiarClave)
                    .addComponent(btLimpiar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreUsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreUsrActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btCambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCambiarClaveActionPerformed
        // rpoceso de cambio de clave
        String cuenta = tfCuentausr.getText();
        String nclave = String.valueOf(pfpass1.getPassword());
        //String nclave2 = String.valueOf(pfpass2.getPassword());
        ConexionBase c = new ConexionBase();
        try{
            c.conectar();
            if (claveValida()){
                Usuario u = c.obtenerDatosUsuario(cuenta);
                c.cambiarClaveUsuario(u);
                System.out.println("Cambio de clave exitosa");
                JOptionPane.showMessageDialog(this,"Se realizo cambio de clave.", "Edición Clave",JOptionPane.INFORMATION_MESSAGE);
            }else{
                System.out.println("error en cambio de clave");
                JOptionPane.showMessageDialog(this,"Ocurrió un error al cambiar la clave.", "Error",JOptionPane.ERROR_MESSAGE);            
            }
        }catch (Exception e){
            System.out.println(e);
        }
        c.desconectar();
    }//GEN-LAST:event_btCambiarClaveActionPerformed

    private void tfCuentausrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCuentausrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCuentausrActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void limpiar(){
        pfpass1.setText("");
        pfpass2.setText("");
    }
    
    private boolean claveValida(){
        String p1 = String.valueOf(pfpass1.getPassword());
        String p2 = String.valueOf(pfpass2.getPassword());
        if (p1==p2 && p1!=""){
            return true;
        }else{
            return false;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCambiarClave;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pfpass1;
    private javax.swing.JPasswordField pfpass2;
    private javax.swing.JTextField tfCuentausr;
    private javax.swing.JTextField tfNombreUsr;
    // End of variables declaration//GEN-END:variables

}
