/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Objetos.Cliente;
import Objetos.Ingrediente;
import bd.ConexionBase;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian
 */
public class frmEdicionIngredientes extends javax.swing.JFrame {

    /**
     * Creates new form frmIngresarIngrediente
     */
    
    frmMantenimientoIngredientes frmMantIng;
    
    public frmEdicionIngredientes(String id, String nombre, frmMantenimientoIngredientes frm) {
        initComponents();
        this.frmMantIng=frm;
        tfid.setText(id);
        tfnombre.setText(nombre);
        
        //cargando datos de cliente a editar
        ConexionBase c = new ConexionBase();
        try{
            c.conectar();
            ArrayList<Ingrediente> ing = c.consultarIngredientes("","ingrediente");
            c.desconectar();
            
            for (Ingrediente ie:ing){
                if(String.valueOf(ie.getId()).equals(id)){
                   tfnombre.setText(nombre);
                   tfdescripcion.setText("");
                   //cbtipo.setText("");
                   tfcosto_porcion.setText("");
                   tfcantidad.setText("");
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrió un error al consultar los datos del registro","Edición",JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfdescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbtipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tfcosto_porcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfcantidad = new javax.swing.JTextField();
        cblimpiar = new javax.swing.JButton();
        cbeditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edicion de Ingredientes");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Descripcion:");

        jLabel3.setText("Tipo:");

        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruta", "Verdura", "Cereal", "Lacteo", "Carne" }));

        jLabel4.setText("Costo de Porcion:");

        tfcosto_porcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcosto_porcionActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad:");

        tfcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcantidadActionPerformed(evt);
            }
        });

        cblimpiar.setText("Limpiar");
        cblimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblimpiarActionPerformed(evt);
            }
        });

        cbeditar.setText("Editar");
        cbeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbeditarActionPerformed(evt);
            }
        });

        jLabel6.setText("Id:");

        tfid.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfcantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfcosto_porcion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbtipo, javax.swing.GroupLayout.Alignment.LEADING, 0, 74, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfdescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(tfnombre))
                            .addComponent(cbeditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cblimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfcosto_porcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cblimpiar)
                    .addComponent(cbeditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfcosto_porcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcosto_porcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcosto_porcionActionPerformed

    private void tfcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcantidadActionPerformed

    private void cblimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_cblimpiarActionPerformed

    private void cbeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbeditarActionPerformed
        // TODO add your handling code here:
        if (validarFormInIngrediente()){
            int id = Integer.parseInt(tfid.getText());
            String nombre = tfnombre.getText();
            String descripcion = tfdescripcion.getText();
            String tipo = cbtipo.getSelectedItem().toString();
            float costo_p = Float.parseFloat(tfcosto_porcion.getText());
            int cant = Integer.parseInt(tfcantidad.getText());
            
            Ingrediente i = new Ingrediente(id,nombre, descripcion, tipo, costo_p, cant);
            ConexionBase c =new ConexionBase();
            
            try{
                c.conectar();
                if(c.modificarIngrediente(i)){
                    System.out.println("ingrediente ingresado.");
                    limpiar();
                    JOptionPane.showMessageDialog(null,"Ingrediente Editado Correctamente.");
                    this.dispose();
                }else{
                    System.out.println("Ingrediente no ingresado.");
                    JOptionPane.showMessageDialog(null,"Información Incorrecta.","Ingreso de Ingredientes",JOptionPane.ERROR_MESSAGE);
                }
            }catch(Exception e){
                System.out.println(e);
            }
            c.desconectar();
        }
    }//GEN-LAST:event_cbeditarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void limpiar(){
        tfnombre.setText("");
        tfdescripcion.setText("");
        tfcosto_porcion.setText("");
        tfcantidad.setText("");
    }
    
    private boolean validarFormInIngrediente(){
        if (tfnombre.getText().equals("") ||
            tfdescripcion.getText().equals("") ||
            tfcosto_porcion.getText().equals("") ||
            tfcantidad.getText().equals("") ){
            JOptionPane.showMessageDialog(null,"Formulario Incorrecto.","Ingreso de Ingredientes",JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbeditar;
    private javax.swing.JButton cblimpiar;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfcantidad;
    private javax.swing.JTextField tfcosto_porcion;
    private javax.swing.JTextField tfdescripcion;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfnombre;
    // End of variables declaration//GEN-END:variables
}
