/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import bd.ConexionBase;
import java.util.ArrayList;
import sun.security.util.PropertyExpander;
import Objetos.Cliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Funciones.*;

/**
 *
 * @author Julian
 */
public class frmVisualizarOrdenes extends javax.swing.JFrame {

    /**
     * Creates new form frmMantenimientoClientes
     */
    public frmVisualizarOrdenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTipoConsulta = new javax.swing.JComboBox<>();
        tfdescripcion = new javax.swing.JTextField();
        btConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btVerOrden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento de Clientes");

        cbTipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Fecha" }));

        tfdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdescripcionActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Fecha", "Usuario", "Cliente", "Estado", "Cantidad", "Productos", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        btVerOrden.setText("Ver Orden");
        btVerOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 255, Short.MAX_VALUE)
                .addComponent(btVerOrden)
                .addGap(293, 293, 293))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 100, Short.MAX_VALUE)
                        .addComponent(cbTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(tfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btConsultar)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btVerOrden)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdescripcionActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        // TODO add your handling code here:
        if(formularioConsultaValidoA()){
            consultarRegistro();}
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btVerOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerOrdenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btVerOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void consultarRegistro(){
        String tipo = cbTipoConsulta.getSelectedItem().toString();
        String descripcion = tfdescripcion.getText();
        
        //consultar
        try{
            //cunsolta a la base
            try{
                ConexionBase c = new ConexionBase();
                c.conectar();
                
                ArrayList<Cliente> registro = c.consultarClientes("","cliente");
                ArrayList<Cliente> resultado = new ArrayList<Cliente>();
                
                if (tipo.equals("Todos")){
                    resultado = registro;
                }else{
                    for (Cliente c1:registro){
                        if(tipo.equals("Cedula")){
                            if(c1.getCedula().contains(descripcion)){
                                resultado.add(c1);
                            }
                        }else if(tipo.equals("Nombres")){
                            if(c1.getNombres().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(c1);
                            }
                        }else if(tipo.equals("Apellidos")){
                            if(c1.getApellidos().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(c1);
                            }
                        }
                    }
                    //System.out.println("consulta invalida...");
                }
                DefaultTableModel dtm = (DefaultTableModel)tablaClientes.getModel();
                dtm.setRowCount(0);
                
                //recorriendo base de datos
                for (Cliente cli:resultado){
                    Object[] fila = new Object[10];
                    fila[0] = cli.getId();
                    fila[1] = cli.getCedula();
                    fila[2] = cli.getNombres();
                    fila[3] = cli.getApellidos();
                    fila[4] = cli.getDireccion();
                    fila[5] = cli.getTelefono();
                    fila[6] = cli.getCorreo();
                    fila[7] = cli.getEdad();
                    fila[8] = cli.getFecha_nacimiento();
                    fila[9] = cli.getTipo();
                    dtm.addRow(fila);
                }
            c.desconectar();
            }catch (Exception e){
                System.out.println("error al consultar clientes");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrió un error al consultar los registros","Consulta",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean seleccionEdicionValida(){
        int n = tablaClientes.getSelectedRowCount();
        if(n!=1){
            JOptionPane.showMessageDialog(this,"Debe seleccionar un registro para editar","Edición",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    
    }
    
    private boolean seleccionEliminacionValida(){ 
        int n = tablaClientes.getSelectedRowCount();
        if(n==0){
            JOptionPane.showMessageDialog(this,"Debe seleccionar mínimo un registro para eliminar","Eliminación",JOptionPane.ERROR_MESSAGE);
            return false;        
        }
        int op = JOptionPane.showConfirmDialog(this, "Está seguro de eliminar los registros seleccionados?","Eliminación",JOptionPane.YES_NO_OPTION);
        if(op==0)
            return true;
        else
            return false;
    }

    private boolean formularioConsultaValidoA(){
        String tipo = cbTipoConsulta.getSelectedItem().toString();
        String descripcion = tfdescripcion.getText();
        if(tipo.equals("Cedula") && descripcion.equals("")){
                JOptionPane.showMessageDialog(this,"Debe ingresar un número","Consulta",JOptionPane.ERROR_MESSAGE);
                return false;
        }else if(tipo.equals("Nombres") && descripcion.equals("")){
                JOptionPane.showMessageDialog(this,"Debe ingresar un Nombre","Consulta",JOptionPane.ERROR_MESSAGE);
                return false;
        }else if(tipo.equals("Apellidos") && descripcion.equals("")){
                JOptionPane.showMessageDialog(this,"Debe ingresar un Apellido","Consulta",JOptionPane.ERROR_MESSAGE);
                return false;
        }
        
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btVerOrden;
    private javax.swing.JComboBox<String> cbTipoConsulta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField tfdescripcion;
    // End of variables declaration//GEN-END:variables
}
